services:
  dt-db:
    image: mysql:latest
    container_name: dt-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dt_db
    ports:
      - "23306:3306"
    volumes:
      - db-data:/var/lib/mysql

  dt-redis:
    image: redis:latest
    container_name: dt-redis
    command: redis-server --requirepass 1234
    ports:
      - "26379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
